2021-06-22 01:38:07.244663 (MainThread): Running with dbt=0.19.1
2021-06-22 01:38:07.280451 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.run.RunTask'>, debug=False, defer=None, exclude=None, fail_fast=False, full_refresh=False, log_cache_events=False, log_format='default', models=None, partial_parse=None, profile=None, profiles_dir='/Users/joshuasprow/.dbt', project_dir=None, record_timing_info=None, rpc_method='run', selector_name=None, single_threaded=False, state=None, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, use_colors=None, vars='{}', version_check=True, warn_error=False, which='run', write_json=True)
2021-06-22 01:38:07.281307 (MainThread): Tracking: tracking
2021-06-22 01:38:07.290400 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f5dbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f8ad90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fac610>]}
2021-06-22 01:38:07.297958 (MainThread): Partial parsing not enabled
2021-06-22 01:38:07.298637 (MainThread): Parsing macros/catalog.sql
2021-06-22 01:38:07.301287 (MainThread): Parsing macros/relations.sql
2021-06-22 01:38:07.302256 (MainThread): Parsing macros/adapters.sql
2021-06-22 01:38:07.313068 (MainThread): Parsing macros/materializations/snapshot_merge.sql
2021-06-22 01:38:07.315013 (MainThread): Parsing macros/core.sql
2021-06-22 01:38:07.317145 (MainThread): Parsing macros/materializations/helpers.sql
2021-06-22 01:38:07.321915 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-06-22 01:38:07.322824 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-06-22 01:38:07.332401 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-06-22 01:38:07.351015 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-06-22 01:38:07.362085 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-06-22 01:38:07.363028 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-06-22 01:38:07.366174 (MainThread): Parsing macros/materializations/common/merge.sql
2021-06-22 01:38:07.373666 (MainThread): Parsing macros/materializations/table/table.sql
2021-06-22 01:38:07.377304 (MainThread): Parsing macros/materializations/view/view.sql
2021-06-22 01:38:07.380645 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-06-22 01:38:07.383161 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-06-22 01:38:07.383638 (MainThread): Parsing macros/etc/query.sql
2021-06-22 01:38:07.384153 (MainThread): Parsing macros/etc/is_incremental.sql
2021-06-22 01:38:07.384974 (MainThread): Parsing macros/etc/datetime.sql
2021-06-22 01:38:07.389574 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-06-22 01:38:07.390566 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-06-22 01:38:07.391502 (MainThread): Parsing macros/adapters/common.sql
2021-06-22 01:38:07.414483 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-06-22 01:38:07.415452 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-06-22 01:38:07.416213 (MainThread): Parsing macros/schema_tests/unique.sql
2021-06-22 01:38:07.417074 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-06-22 01:38:07.421002 (MainThread): Partial parsing not enabled
2021-06-22 01:38:07.461787 (MainThread): [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.jaffle_shop.example

2021-06-22 01:38:07.461880 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '22792096-1510-4ba0-be17-84992af9cfdf', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10819adf0>]}
2021-06-22 01:38:07.463525 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '22792096-1510-4ba0-be17-84992af9cfdf', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10816cbb0>]}
2021-06-22 01:38:07.463637 (MainThread): Found 0 models, 0 tests, 0 snapshots, 0 analyses, 138 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-06-22 01:38:07.463826 (MainThread): WARNING: Nothing to do. Try checking your model configs and model specification args
2021-06-22 01:38:07.463912 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1081524c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1081520d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108163ee0>]}
2021-06-22 01:38:07.463978 (MainThread): Flushing usage events
2021-06-22 01:38:07.517747 (MainThread): Encountered an error:
2021-06-22 01:38:07.517884 (MainThread): Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
2021-06-22 01:38:07.519654 (MainThread): Traceback (most recent call last):
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/opt/homebrew/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/main.py", line 229, in track_run
    dbt.tracking.flush()
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/tracking.py", line 428, in flush
    tracker.flush()
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/snowplow_tracker/tracker.py", line 218, in flush
    emitter.sync_flush()
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/snowplow_tracker/emitters.py", line 182, in sync_flush
    Emitter.flush(self)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/snowplow_tracker/emitters.py", line 149, in flush
    self.send_events(self.buffer)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/snowplow_tracker/emitters.py", line 206, in send_events
    status_code = self.http_post(data).status_code
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/dbt/tracking.py", line 68, in http_post
    r = requests.post(
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 343, in connect
    self.ssl_context = create_urllib3_context(
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 290, in create_urllib3_context
    context.verify_mode = cert_reqs
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 438, in verify_mode
    self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1028, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/opt/homebrew/Cellar/dbt/0.19.1_1/libexec/lib/python3.8/site-packages/OpenSSL/SSL.py", line 331, in __init__
    self.callback = _ffi.callback(
MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks

2021-06-22 01:38:07.519797 (MainThread): unclosed <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.206', 58494), raddr=('34.199.231.102', 443)>
